/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Crawler */

#ifndef _Included_Crawler
#define _Included_Crawler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Crawler
 * Method:    crawler
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Crawler_crawler
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
